#!/usr/bin/env python3
"""
SFAAM NEWS — Local Development Setup & Runner
================================================
This script:
  1. Creates a virtual environment (if not exists)
  2. Installs all dependencies
  3. Creates a local .env file (if not exists)
  4. Generates admin credentials
  5. Starts the server on http://localhost:8000

Usage:
    python run_local.py          # Full setup + run
    python run_local.py --run    # Skip setup, just run
    python run_local.py --setup  # Just setup, don't run
"""

import os
import sys
import subprocess
import hashlib
import secrets

# ─── Config ───
VENV_DIR = "venv"
ENV_FILE = ".env"
DB_FILE = "sfaam_local.db"
PORT = 8000
HOST = "0.0.0.0"


def run(cmd, **kwargs):
    """Run a command and exit on failure."""
    print(f"  > {cmd}")
    result = subprocess.run(cmd, shell=True, **kwargs)
    if result.returncode != 0:
        print(f"  ✗ Command failed with exit code {result.returncode}")
        sys.exit(1)
    return result


def get_python():
    """Return the venv python path."""
    if sys.platform == "win32":
        return os.path.join(VENV_DIR, "Scripts", "python.exe")
    return os.path.join(VENV_DIR, "bin", "python")


def get_pip():
    """Return the venv pip path."""
    if sys.platform == "win32":
        return os.path.join(VENV_DIR, "Scripts", "pip.exe")
    return os.path.join(VENV_DIR, "bin", "pip")


def step1_create_venv():
    """Create virtual environment."""
    if os.path.exists(VENV_DIR):
        print(f"\n✓ Virtual environment already exists ({VENV_DIR}/)")
        return
    print(f"\n{'='*60}")
    print("STEP 1: Creating Virtual Environment")
    print(f"{'='*60}")
    run(f'"{sys.executable}" -m venv {VENV_DIR}')
    print("✓ Virtual environment created!")


def step2_install_deps():
    """Install Python dependencies."""
    pip_path = get_pip()
    print(f"\n{'='*60}")
    print("STEP 2: Installing Dependencies")
    print(f"{'='*60}")
    run(f'"{pip_path}" install --upgrade pip')
    run(f'"{pip_path}" install -r requirements.txt')
    print("✓ All dependencies installed!")


def step3_create_env():
    """Create .env file for local development."""
    if os.path.exists(ENV_FILE):
        print(f"\n✓ .env file already exists")
        return

    print(f"\n{'='*60}")
    print("STEP 3: Creating .env File")
    print(f"{'='*60}")

    # V31: Generate a RANDOM admin password (no more hardcoded password!)
    # Old versions hardcoded "Admin-SFAAM-2026!" — anyone with the source could log in.
    password = secrets.token_urlsafe(18)  # ~24-char base64-url password
    # V31: Salted PBKDF2 hash (resistant to rainbow tables, unlike plain SHA-256)
    salt = secrets.token_bytes(16)
    pw_hash = f"{salt.hex()}${hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 200_000).hex()}"
    api_key = secrets.token_urlsafe(32)

    env_content = f"""# ============================================================
# SFAAM NEWS — LOCAL DEVELOPMENT CONFIGURATION
# ============================================================
# Auto-generated by run_local.py
# ------------------------------------------------------------

# ─── CORE ────────────────────────────────────────────────────
SITE_URL=http://localhost:{PORT}
HOST={HOST}
PORT={PORT}

# ─── DATABASE (SQLite for local dev — no PostgreSQL needed) ──
DATABASE_URL=sqlite+aiosqlite:///./{DB_FILE}
ENV=development

# ─── ADMIN AUTH ──────────────────────────────────────────────
ADMIN_PASSWORD_HASH={pw_hash}
ADMIN_KEY={api_key}

# ─── REDIS (NOT needed for local dev — uses in-memory) ──────
# Leave empty — the app automatically falls back to in-memory

# ─── DRAFT MODE ──────────────────────────────────────────────
# 1 = Admin must publish articles manually
# 0 = Articles auto-publish immediately
DRAFT_MODE=0

# ─── AI KEYS (REQUIRED for full article generation) ──────────
# Without these, articles use raw RSS summary only.
# Get Groq keys (FREE): https://console.groq.com/keys
# Get Gemini keys (FREE): https://aistudio.google.com/apikey

# World
GROQ_KEY_WORLD=
GEMINI_KEY_WORLD=

# USA
GROQ_KEY_USA=
GEMINI_KEY_USA=

# UK
GROQ_KEY_UK=
GEMINI_KEY_UK=

# Pakistan
GROQ_KEY_PAKISTAN=
GEMINI_KEY_PAKISTAN=

# India
GROQ_KEY_INDIA=
GEMINI_KEY_INDIA=

# Germany
GROQ_KEY_GERMANY=
GEMINI_KEY_GERMANY=

# ─── TRENDS PIPELINE ─────────────────────────────────────────
TRENDS_GEO=
TRENDS_LIMIT=7
TRENDS_MAX_SOURCES=5
TRENDS_MIN_FACTS=2
TRENDS_INTERVAL_HOURS=6
TRENDS_RUN_ON_STARTUP=1
TRENDS_AI_PROVIDER=auto

# ─── QUALITY CONTROL ─────────────────────────────────────────
QC_MIN_SCORE=60
QC_MIN_READABILITY=40

# ─── FEATURES ────────────────────────────────────────────────
ENABLE_TRANSLATION=1
ENABLE_TTS=1
CSRF_ENABLED=0

# ─── SCHEDULER ───────────────────────────────────────────────
# News fetching interval (minutes)
# SCHEDULER_INTERVAL=60
"""
    with open(ENV_FILE, "w") as f:
        f.write(env_content)

    print(f"✓ .env file created!")
    print(f"\n  🔑 ADMIN LOGIN CREDENTIALS:")
    print(f"     URL:      http://localhost:{PORT}/admin.html")
    print(f"     Password: {password}")
    print(f"     API Key:  {api_key}")
    print(f"\n  ⚠ Save these credentials! They won't be shown again.")


def step4_start_server():
    """Start the Uvicorn server."""
    python_path = get_python()

    print(f"\n{'='*60}")
    print(f"STEP 4: Starting SFAAM NEWS Server")
    print(f"{'='*60}")
    print(f"\n  🌐 Website:  http://localhost:{PORT}")
    print(f"  🔧 Admin:    http://localhost:{PORT}/admin.html")
    print(f"  📡 API:      http://localhost:{PORT}/api/articles")
    print(f"  ❤️  Health:   http://localhost:{PORT}/health")
    print(f"\n  Press Ctrl+C to stop the server.")
    print(f"{'='*60}\n")

    # Use exec to replace this process with uvicorn (clean shutdown)
    os.execv(
        python_path,
        [python_path, "-m", "uvicorn", "main:app",
         "--host", HOST, "--port", str(PORT), "--reload"]
    )


def main():
    print("""
╔══════════════════════════════════════════════════════╗
║            SFAAM NEWS — Local Setup                 ║
║     Zero-Hallucination Factual News Platform        ║
╚══════════════════════════════════════════════════════╝
""")

    mode = "--run" if len(sys.argv) < 2 else sys.argv[1]

    if mode == "--setup":
        step1_create_venv()
        step2_install_deps()
        step3_create_env()
        print("\n✅ Setup complete! Run 'python run_local.py --run' to start.")
    elif mode == "--run":
        if not os.path.exists(VENV_DIR):
            print("✗ Virtual environment not found. Run 'python run_local.py' first.")
            sys.exit(1)
        step4_start_server()
    else:
        # Full setup + run
        step1_create_venv()
        step2_install_deps()
        step3_create_env()
        step4_start_server()


if __name__ == "__main__":
    main()
